import type { Metadata } from "next";
import { LegalPage, PrivacyContact } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Política de privacidad", description: "Información RGPD sobre el tratamiento de datos en FluxBot." };

export default function PrivacyPage() {
  return <LegalPage eyebrow="RGPD y privacidad" title="Política de privacidad" summary="Explicamos qué datos tratamos, para qué y cómo pueden ejercer sus derechos las personas y los comercios que usan FluxBot." sections={[
    { title: "Roles y alcance", content: <p>FluxBot Studio IA presta una plataforma de comercio conversacional. Para los datos de visitantes de una tienda, el comercio es normalmente responsable del tratamiento y FluxBot actúa como encargado siguiendo sus instrucciones. Para datos de cuenta, facturación, soporte y seguridad de FluxBot, FluxBot actúa como responsable.</p> },
    { title: "Datos y finalidades", content: <><p>Podemos tratar datos de cuenta y contacto, configuración de la tienda, catálogo sincronizado, mensajes intercambiados con el asistente, identificadores técnicos y registros de seguridad. Los usamos para prestar el servicio, responder conversaciones, mantener la seguridad, prevenir abuso, atender soporte, cumplir obligaciones legales y mejorar el producto de forma compatible con la configuración contratada.</p><p>No vendemos datos personales ni usamos el contenido de conversaciones para fines publicitarios de terceros.</p></> },
    { title: "Base jurídica, destinatarios y transferencias", content: <><p>El tratamiento se basa en la ejecución del contrato, el interés legítimo en seguridad y mejora del servicio, el cumplimiento de obligaciones legales y, cuando corresponda, el consentimiento. Los proveedores de alojamiento, comunicaciones, analítica contratada y modelos de IA solo acceden a datos cuando es necesario para prestar el servicio y bajo compromisos de confidencialidad y protección de datos.</p><p>Cuando exista una transferencia internacional, se aplicarán las garantías exigibles, como cláusulas contractuales tipo u otra base válida. La relación vigente de subencargados puede solicitarse mediante el <PrivacyContact />.</p></> },
    { title: "Conservación y seguridad", content: <p>Conservamos la información durante la relación contractual y el periodo necesario para cumplir obligaciones legales, resolver incidencias y aplicar la retención configurada por el comercio. Aplicamos medidas técnicas y organizativas razonables, como control de acceso, cifrado en tránsito, segregación por comercio y registros limitados de seguridad.</p> },
    { title: "Derechos y solicitudes Shopify", content: <><p>Puede solicitar acceso, rectificación, supresión, oposición, limitación, portabilidad o retirar un consentimiento, cuando corresponda. Los visitantes deben contactar primero con la tienda con la que interactuaron; el comercio puede trasladar la solicitud a FluxBot. Para una solicitud relacionada con FluxBot, use el <PrivacyContact />.</p><p>Las aplicaciones públicas de Shopify deben atender los webhooks <code>customers/data_request</code>, <code>customers/redact</code> y <code>shop/redact</code>. FluxBot diseña su operativa para confirmar estas solicitudes y completar la acción dentro de los plazos aplicables, salvo obligación legal de conservación.</p></> },
    { title: "Reclamaciones y cambios", content: <p>Puede reclamar ante la autoridad de protección de datos competente, incluida la AEPD en España. Actualizaremos esta página cuando cambie el servicio o la normativa aplicable.</p> },
  ]} />;
}
